# Generated by Django 4.1.1 on 2022-09-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.PositiveIntegerField()),
                ('create_date', models.TimeField(auto_now_add=True)),
                ('update_date', models.TimeField(auto_now=True)),
                ('genre', models.CharField(choices=[('Comedy', 'COMEDY'), ('Horror', 'HORROR'), ('Fantasy', 'FANTASY'), ('Romans', 'ROMANS')], max_length=100)),
            ],
        ),
    ]
