# Generated by Django 4.1.1 on 2022-09-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_bookcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_detail',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
